- hosts: kvm01
  tags: provision
  vars:
    kvm_vm_hostname: "vm1osisoft"
    kvm_vm_public_ip: 10.11.100.35
    kvm_vm_root_pwd: "p@ssw0rd"
    kvm_vm_base_img: f34-lab01.qcow2
    kvm_vm_vcpus: "2"
    kvm_vm_ram: "4096"
    kvm_vm_os_disk_name: "{{ kvm_vm_hostname }}"
    kvm_vm_os_disk_size: "10G"
    kvm_vm_nics:
      - name: eth0
        bootproto: static
        onboot: yes
        ip: "{{ kvm_vm_public_ip }}"
        prefix: "24"
        gateway: "10.11.100.1"
        dns_server: "8.8.8.8"
        config: "--type network --source default --model virtio"
  tasks:
    - name: Create KVM VM
